{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "app.shortname" . }}-golangapp-vs
  labels:
  {{- include "golangapp.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.istio.gateway.hostname }}
  gateways:
    - {{ template "app.shortname" . }}-gateway
  http:
    - match:
        - uri:
            prefix:  {{ .Values.golangapp.istio.gateway.path }}
      route:
        - destination:
            host: {{ template "app.shortname" . }}-golangapp
            port:
              number: {{ .Values.golangapp.service.port }}
  {{- end }}