{{- if .Values.golangapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "app.shortname" . }}-golangapp
  labels:
  {{- include "golangapp.labels" . | nindent 4 }}
  annotations:
      {{- if .Values.golangapp.ingress.certManager }}
      kubernetes.io/tls-acme: "true"
      {{- end }}
      {{- if .Values.golangapp.ingress.annotations }}
      {{ toYaml .Values.golangapp.ingress.annotations | indent 4 }}
      {{- end }}
spec:
  {{- if .Values.golangapp.ingress.tls }}
  tls:
    {{- range .Values.golangapp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.golangapp.ingress.hostName }}
    - host: {{ tpl .Values.golangapp.ingress.hostName . }}
      http:
    {{- else }}
    - http:
        {{- end }}
        paths:
          - path: {{ .Values.golangapp.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "app.shortname" . }}-golangapp
                port:
                  number: {{ .Values.golangapp.service.port }}
{{- end }}